
helmDefaults:
  kubeContext: elven-project
  createNamespace: true
  cleanupOnFail: true
  wait: false

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: autoscaler
    url: https://kubernetes.github.io/autoscaler
  - name: argocd
    url: https://argoproj.github.io/argo-helm
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns
  - name: deliveryhero
    url: https://charts.deliveryhero.io/

templates:


  metrics-server: &metrics-server
    chart: metrics-server/metrics-server
    namespace: kube-system
    version: 3.11.0
    values: 
    - "charts/metrics-server/values.yaml"

  cluster-autoscaler: &cluster-autoscaler
    chart: autoscaler/cluster-autoscaler
    namespace: kube-system
    version: 9.29.4
    values:
    - "charts/cluster-autoscaler/values.yaml"
  
  # argocd: &argo-cd
  #   chart: argocd/argo
  #   namespace: argocd
  #   values:
  #   - "charts/argocd/values.yaml"
  
  external-dns: &external-dns
    chart: external-dns/external-dns
    namespace: default
    values:
    - "charts/external-dns/values.yaml"
  
  local-dns: &local-dns
    chart: deliveryhero/node-local-dns
    namespace: default
    values:
    - "charts/local-dns/values.yaml"

  prometheus: &prometheus
    chart: prometheus-community/kube-prometheus-stack
    namespace: prometheus
    values:
    - "charts/prometheus/values.yaml"

releases:
  - name: metrics-server
    <<: *metrics-server
  - name: cluster-autoscaler
    <<: *cluster-autoscaler
  - name: external-dns
    <<: *external-dns
  - name: local-dns
    <<: *local-dns   

  - name: prometheus-stack
    <<: *prometheus
  # - name: argocd
  #   <<: *argo-cd



