#set:
#  - name: autoDiscovery.clusterName
#    value: irt-project

# https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler#values
autoDiscovery:
  clusterName: irt-project
awsRegion: us-east-2
image:
  repository: "k8s.gcr.io/autoscaling/cluster-autoscaler"
  tag: "v1.21.3"

#essa | é pra transformar em string
podDisruptionBudget: 
  maxUnavailable: 50%

extraArgs:
  expander: priority

expanderPriorities: |-
  10:
    - irt-project-irt-project-nodegroup-template2022080113405616850000000120220801134056903500000003
  0:
    - .*

rbac: 
  serviceAccount: 
    annotations: 
      "eks.amazonaws.com/role-arn": "arn:aws:iam::035267315123:role/irt-project-autoscaler"
