#set:
#  - name: autoDiscovery.clusterName
#    value: irt-project

# https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler#values
autoDiscovery:
  clusterName: elven-project
awsRegion: us-east-2
image:
  repository: "k8s.gcr.io/autoscaling/cluster-autoscaler"
  tag: "v1.26.2"

#essa | é pra transformar em string
podDisruptionBudget: 
  maxUnavailable: 50%

extraArgs:
  expander: priority

expanderPriorities: |-
  10:
    - apps1
  0:
    - .*

rbac: 
  serviceAccount: 
    annotations: 
      "eks.amazonaws.com/role-arn": "arn:aws:iam::790817841652:role/cluster-autoscaler-role"
